site:
  title: RuboCop
  url: https://docs.rubocop.org/
  start_page: master@rubocop::index.adoc
  keys:
    google_analytics: 'UA-140153536-1'
content:
  sources:
  - url: https://github.com/rubocop-hq/rubocop.git
    branches: ['master']
    tags: []
    start_path: doc
asciidoc:
  attributes:
    linkattrs: ''
    toc: ~
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui
output:
  dir: ./docs
